Update pr-workflow.yml

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -14,40 +14,36 @@ jobs:
     steps:
     - name: Add Comment to Pull Request
       if: github.event.action == 'opened'
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        COMMENT=$(cat <<EOF
-        {
-          "body": "Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. 😊"
-        }
-        EOF
-        )
         RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
           -X POST \
-          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
-          -d "$COMMENT")
+          -d '{"body": "Thank you for submitting your pull request! 🙌 We'\''ll review it as soon as possible. 😊"}' \
+          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments)
+        
         cat response.json
         if [ "$RESPONSE" -ne 201 ]; then
           echo "Failed to add comment"
           exit 1
         fi
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Add Comment to Merged Pull Request
       if: github.event.action == 'closed' && github.event.pull_request.merged == true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
-        COMMENT=$(cat <<EOF
-        {
-          "body": "🎉 Your pull request has been successfully merged! 🎉 Thank you for your valuable contribution to our project. Your efforts are greatly appreciated. Feel free to reach out if you have any more contributions or if there's anything else we can assist you with. Keep up the fantastic work! 🚀"
-        }
-        EOF
-        )
-        curl -X POST \
+        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
+          -X POST \
           -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
-          -d "$COMMENT"
+          -d '{"body": "🎉 Your pull request has been successfully merged! 🎉 Thank you for your valuable contribution to our project. Your efforts are greatly appreciated. Feel free to reach out if you have any more contributions or if there'\''s anything else we can assist you with. Keep up the fantastic work! 🚀"}' \
+          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments)
+        
+        cat response.json
+        if [ "$RESPONSE" -ne 201 ]; then
+          echo "Failed to add merge comment"
+          exit 1
+        fi
